import path from 'node:path';
import { groupByProject, loadIndex, loadSession } from './store.js';
import { redact } from './redact.js';
import type { CanonicalEvent, CanonicalSession } from './types.js';

export type HandoffLevel = 'brief' | 'standard' | 'full';

/**
 * Distill a project's whole timeline (all sessions, all apps, in order)
 * into a handoff document a fresh agent can cold-start from.
 *
 * v0.1 uses structural extraction (no LLM): the user's words are gold and are
 * never paraphrased; outcome lines come from each session's closing assistant
 * message; constraints are mined from user messages by pattern.
 */
export function generateHandoff(projectQuery: string, level: HandoffLevel = 'standard'): string | null {
  const idx = loadIndex();
  const groups = groupByProject(idx);
  const hit = [...groups.entries()].find(([p]) => p.toLowerCase().includes(projectQuery.toLowerCase()));
  if (!hit) return null;
  const [project, entries] = hit;

  const sessions = entries
    .map((e) => loadSession(e.id))
    .filter((s): s is CanonicalSession => s !== null);
  if (sessions.length === 0) return null;

  const out: string[] = [];
  const now = new Date().toISOString().slice(0, 16).replace('T', ' ');
  const sources = [...new Set(sessions.map((s) => s.meta.source))].join(', ');

  out.push(`# Project Handoff: ${path.basename(project)}`);
  out.push(`> generated by session-bus @ ${now} · ${sessions.length} session(s) · sources: ${sources}`);
  out.push(`> project dir: ${project}`);
  out.push('');

  // Advisory sessions (pure Q&A about the project, no file changes) stay on
  // the timeline but must not pose as "the latest work" — a fresh agent would
  // otherwise mistake an answered question for the project's current state.
  const working = sessions.filter((s) => !isAdvisory(s));
  const lastWorking = working[working.length - 1] ?? sessions[sessions.length - 1];

  // 1. Goal & current state
  out.push(`## 1. 目标与现状`);
  const firstAsk = firstUserMessage(sessions[0]);
  const lastOutcome = lastAssistantMessage(lastWorking);
  out.push(`**项目起点(用户原话):**`);
  out.push(quote(firstAsk, level === 'brief' ? 300 : 1200));
  if (lastOutcome) {
    out.push(`**最近一次工作的收尾(agent 原话):**`);
    out.push(quote(lastOutcome, level === 'brief' ? 300 : 1200));
  }
  out.push('');

  // 2. Timeline
  out.push(`## 2. 会话时间线`);
  for (const s of sessions) {
    const m = s.meta;
    const sameDay = (m.startedAt ?? '').slice(0, 10) === (m.endedAt ?? '').slice(0, 10);
    const span = `${(m.startedAt ?? '?').slice(0, 16).replace('T', ' ')} → ${sameDay ? (m.endedAt ?? '?').slice(11, 16) : (m.endedAt ?? '?').slice(0, 16).replace('T', ' ')}`;
    out.push(`### ${m.id} · ${span} · ${m.source}${isAdvisory(s) ? ' · (咨询/查询会话,未改动文件)' : ''}`);
    out.push(`**任务:** ${m.title}`);
    if (level !== 'brief') {
      const ask = firstUserMessage(s);
      if (ask && ask !== m.title) out.push(`**用户原话(开场):** ${quoteInline(ask, 500)}`);
      const closing = lastAssistantMessage(s);
      if (closing) out.push(`**收尾(agent):** ${quoteInline(closing, 500)}`);
      if (m.filesTouched.length) out.push(`**改动文件:** ${m.filesTouched.slice(0, 15).map((f) => displayPath(f, project)).join(', ')}${m.filesTouched.length > 15 ? ` …(+${m.filesTouched.length - 15})` : ''}`);
      const stats: string[] = [];
      if (m.counts.toolCalls) stats.push(`${m.counts.toolCalls} 次工具调用`);
      if (m.counts.compactions) stats.push(`${m.counts.compactions} 次上下文压缩`);
      if (stats.length) out.push(`*${stats.join(' · ')}*`);
    }
    if (level === 'full') {
      out.push('', `**逐轮纪要:**`);
      for (const e of conversationTurns(s)) {
        const who = e.role === 'user' ? '👤' : '🤖';
        out.push(`- ${who} ${quoteInline(e.text ?? '', 300)}`);
      }
    }
    out.push('');
  }

  // 3. Constraints & preferences mined from user messages
  const constraints = mineConstraints(sessions);
  if (constraints.length) {
    out.push(`## 3. 用户明确提出的约束/偏好(原话,跨全部会话)`);
    for (const c of constraints.slice(0, level === 'brief' ? 4 : 15)) {
      out.push(`- ${quoteInline(c, level === 'brief' ? 160 : 280)}`);
    }
    out.push('');
  }

  // 4. Open threads — taken from the last *working* session, not a Q&A one
  out.push(`## 4. 接手注意`);
  const lastUser = lastUserMessage(lastWorking);
  if (lastUser) {
    out.push(`最后一条用户消息(很可能是未尽事项):`);
    out.push(quote(lastUser, level === 'brief' ? 300 : 600));
  }
  out.push('');

  // 5. Files (skipped at brief level — get them from the standard handoff)
  const allFiles = level === 'brief' ? [] : [...new Set(sessions.flatMap((s) => s.meta.filesTouched))];
  if (allFiles.length) {
    out.push(`## 5. 文件足迹(共 ${allFiles.length} 个)`);
    out.push(allFiles.slice(0, 30).map((f) => `- ${displayPath(f, project)}`).join('\n'));
    if (allFiles.length > 30) out.push(`- …(+${allFiles.length - 30})`);
    out.push('');
  }

  // 6. How to dig deeper
  out.push(`## 6. 查证细节的方法`);
  out.push(`本文档是蒸馏结果。完整逐字历史可通过 session-bus MCP 工具按需检索:`);
  out.push(`- \`list_sessions(project="${path.basename(project)}")\` — 会话清单`);
  out.push(`- \`get_session(id, offset, limit)\` — 逐字读取任意会话(分页)`);
  out.push(`- \`search_sessions(query)\` — 全文搜索用户/agent 原话`);
  out.push(`会话 ID:${sessions.map((s) => s.meta.id).join(', ')}`);

  return redact(out.join('\n'));
}

/* ----------------------------- extraction helpers ----------------------------- */

function isRealMessage(e: CanonicalEvent): boolean {
  return e.type === 'message' && !!e.text?.trim();
}

/** Pure consultation: nothing was built or changed — likely "what happened?" Q&A. */
export function isAdvisory(s: CanonicalSession): boolean {
  return s.meta.filesTouched.length === 0 && s.meta.counts.toolCalls <= 15;
}

function firstUserMessage(s: CanonicalSession): string {
  return s.events.find((e) => e.role === 'user' && isRealMessage(e))?.text ?? '';
}

function lastUserMessage(s: CanonicalSession): string {
  return [...s.events].reverse().find((e) => e.role === 'user' && isRealMessage(e))?.text ?? '';
}

function lastAssistantMessage(s: CanonicalSession): string {
  return [...s.events].reverse().find((e) => e.role === 'assistant' && isRealMessage(e))?.text ?? '';
}

function conversationTurns(s: CanonicalSession): CanonicalEvent[] {
  return s.events.filter((e) => (e.role === 'user' || e.role === 'assistant') && isRealMessage(e));
}

const CONSTRAINT_RE = /(不要|别用|不能|必须|一定要|注意|要求|希望你|记住|don'?t|must|always|never|make sure)/i;

function mineConstraints(sessions: CanonicalSession[]): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  for (const s of sessions) {
    for (const e of s.events) {
      if (e.role !== 'user' || !isRealMessage(e)) continue;
      for (const sentence of splitSentences(e.text!)) {
        if (sentence.length < 8 || sentence.length > 300) continue;
        if (!CONSTRAINT_RE.test(sentence)) continue;
        const key = sentence.slice(0, 60);
        if (seen.has(key)) continue;
        seen.add(key);
        found.push(sentence.trim());
      }
    }
  }
  return found;
}

function splitSentences(text: string): string[] {
  return text.split(/(?<=[。！？!?；;\n])/).map((s) => s.trim()).filter(Boolean);
}

function quote(text: string, cap: number): string {
  const t = text.trim();
  const cut = t.length > cap ? `${t.slice(0, cap)}…` : t;
  return cut.split('\n').map((l) => `> ${l}`).join('\n');
}

function displayPath(f: string, project: string): string {
  return f.startsWith(project + path.sep) ? path.relative(project, f) : f;
}

function quoteInline(text: string, cap: number): string {
  const t = text.replace(/\s+/g, ' ').trim();
  return t.length > cap ? `${t.slice(0, cap)}…` : t;
}
